### ISSUE TITLE
DTraceProviderBindings.node issue

### ISSUE THREAD

**Issue by jordancclive** [tea3/hexo-related-popular-posts#1]
I can't get this plugin to work. Here's the error message I get:

Error: The module '/usr/local/lib/node_modules/hexo-cli/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

**Comment by jordancclive** [comment]
I tried both npm rebuild and npm install - neither worked.

**Comment by NoahDragon** [comment]
Can you try to remove the node-modules folder and rerun the `npm install`?

**Comment by tea3** [comment]
Is it possible to solve  follow as ? Also , please refer what NoahDragon taught .
https://github.com/hexojs/hexo/issues/1055
http://stackoverflow.com/questions/40368058/atom-package-manager-not-working

**Comment by noscripter** [comment]
You can fix this problem by doing this in Mac os:

1.  cd hexo installation directory

```
cd `which hexo`/../..
```

2. remove installed node modules

`rm -rvf node_modules`

3. reinstall all dependencies

`npm install`

>  if you're in china, please use `cnpm i` which provides faster installation speed.

**Comment by tea3** [comment]
@noscripter Thank you . The advice from you was very helpful.
@jordancclive Would it be possible to solve this issue ?

**Comment by lauid** [comment]
I failure

**Comment by tea3** [comment]
@liugaohua 

Please try reinstall hexo and plugin. For example , you try following emviroment.

- Mac OSX 10.11 (Sorry , I can't tried windows. )
- node v6.9.4
- npm v4.1.1
- hexo-cli@1.0.2

```
$ nvm install v6.9.4
$ nvm use v6.9.4
$ npm install -g npm
$ npm install -g hexo-cli
$ hexo init hexo694
$ cd hexo694
$ npm install
$ npm install hexo-related-popular-posts --save
$ hexo new sample-post-1
$ hexo new sample-post-2
```

Please edit `sample-post-1.md` as following.

```
title: sample1
permalink: sample-post-1
date: 2017-03-10 20:41:00
tags:
  - hexo
categories:
  - web
---
Hello , world !
```

Please edit  `sample-post-2.md` as following.

```
title: sample2
permalink: sample-post-2
date: 2017-03-10 20:42:00
tags:
  - hexo
categories:
  - web
---
Hello , world !  This post's title is sample2.
```

Next, please follow these instructions.
https://github.com/tea3/hexo-related-popular-posts#usage

Can you solve this issue by this way ?

**Comment by levblanc** [comment]
Got the same problem. My setup:

- Mac OSX: 10.11.6
- NodeJS:    v7.10.0
- npm:          v4.6.1

I use nvm to manage my node versions. Recently I upgraded to v7, and `dtrace-provider` complained about its compilation.

I tried the following steps:

1. uninstall hexo-cli globally

```bash
$ npm uninstall -g hexo-cli
```

2. then reinstall it

```bash
$ npm install -g hexo-cli
```

Till this step, when I went to my hexo blog folder and ran `hexo server`, `dtrace-provider` was still complaining. So I decided to remove all the `node_modules` and reinstall.

3. under your hexo blog folder (where you have `node_modules`, `public`, `scaffolds`, `source` and others), remove `node_modules`

```bash
$ rm -rf node_modules
```

4. then reinstall them all

```bash
$ npm install 
```

You will see `dtrace-provider` has an installation step during npm install as follows:

``` bash
> dtrace-provider@0.8.2 install /path/to/your/blog/folder/node_modules/dtrace-provider
> node scripts/install.js
```

So I think 3 and 4 are the actual steps that resolves `dtrace-provider` complain.

**Comment by tea3** [comment]
@levblanc 
Thank you for the helpful information .

**Comment by re0x6d** [comment]
@levblanc Thank you for the helpful information. I solved this problem by following your advices!

**Comment by ToddAT** [comment]
I had to complete all 4 steps to solve the issue on my local machine. Thanks for the info.

**Comment by ShumRain** [comment]
@levblanc  Thank you, I finally solved.

**Comment by YingshanDeng** [comment]
re-install hexo-cli works

**Comment by MikeMMao** [comment]
Maybe your Global installation files hasn`t been update, please try to update your hexo-cli with command below:

`sudo npm install -g hexo-cli `

this solved my problem.

**Comment by hmgqzx** [comment]
@MikeMMao 
Never run `npm install -g hexo-cli` with `sudo`. Sometimes it would cause some problem with permission. 
You can see more at  [Mac install hexo use sudo but sitll permission denied · Issue #2785 · hexojs/hexo](https://github.com/hexojs/hexo/issues/2785#issuecomment-338391933)

**Comment by youkimm** [comment]
@levblanc  thank you very much,  this sovlved my problem
