### ISSUE TITLE
How to modify the font？

### ISSUE THREAD

**Issue by hoochanlon** [tea3/hexo-related-popular-posts#10]
`{{ popular_posts( {} , post ) }}` generated font is too big

**Comment by tea3** [comment]
@loremwalker 
If you can see your site you can make a detailed suggestion.

Also ,  this plug-in can customize HTML, please read the following items.
https://github.com/tea3/hexo-related-popular-posts/wiki/More-Settings#customize-html

**Comment by hoochanlon** [comment]
@tea3 cool，problem solved
