### ISSUE TITLE
tag_map support

### ISSUE THREAD

**Issue by NomNes** [tea3/hexo-related-popular-posts#12]
`{"title":null,"path":"/null", ...}` if override slug in the `tag_map`

**Comment by tea3** [comment]
@NomNes 

Sorry , Does this problem improve by running `hexo clean` and deleting the cache file?
https://github.com/tea3/hexo-related-popular-posts/wiki/More-Settings#cache

**Comment by NomNes** [comment]
hmm, I'm sure I did) I'm don.t use cache, but `hero clean` is in package.json scripts `"gen": "hexo clean && hexo generate"`
But now everything is fine, thank you)
