### ISSUE TITLE
Feature-Request about list.img

### ISSUE THREAD

**Issue by xaoxuu** [tea3/hexo-related-popular-posts#29]
Hello, I found that the `img` obtained by `hexo-related-popular-posts` can only be automatically read from within the article. May I ask you to add a configuration item according to one of the front-matter How about a custom value such as `headimg` as the summary image of the article?

For example, in "Article 1", the header image of "Article 2" is not perfect. What we want is A, but actually B:

- Article 1: https://xaoxuu.com/blog/2016-09-12-sandbox/
- Article 2: https://xaoxuu.com/blog/2019-08-27-prohud/

![iShot2020-08-26下午06 02 30](https://user-images.githubusercontent.com/16400144/91290965-ef25e380-e7c6-11ea-87ec-759d8a95b88f.jpg)
![iShot2020-08-26下午06 03 57](https://user-images.githubusercontent.com/16400144/91290971-f2b96a80-e7c6-11ea-842b-6be243e9ca4b.jpg)

**Comment by tea3** [comment]
@xaoxuu 
Please specify `eyeCatchImage` and description in frontmatter of markdown file. It is explained in detail issue #13.

Please see the follow about frontmatter.
https://github.com/tea3/hexo-related-popular-posts/wiki/More-Settings#customize-html

**Comment by xaoxuu** [comment]
Can I change the `eyeCatchImage` attribute in the blog's `_config.yml` ? Because the theme already uses other attributes, I have to duplicate the image link.

```yaml
headimg: https://gitee.com/xaoxuu/cdn-assets/raw/master/blog/2019-0827a@2x.jpg
eyeCatchImage: https://gitee.com/xaoxuu/cdn-assets/raw/master/blog/2019-0827a@2x.jpg
```

This attribute may be different in different themes, such as `header_img:` or `cover_img: ` ...

It would be great if it can be customized. 😁

**Comment by tea3** [comment]
@xaoxuu 
I'm sorry. It cannot be specified in `_config.xml`. This attribute is a value specified for each article.

https://github.com/tea3/hexo-related-popular-posts/issues/13#issuecomment-430496487

**Comment by xaoxuu** [comment]
What I mean is, allow users to change `eyeCatchImage` to other attribute names to suit the user's hexo theme, for example:

Edit in `blog/_config.yml`:
```yaml
popularPosts:
  eyeCatchImageAttributeName: themeHeaderImage
```

So users can write in front-matter like this:
```md
---
title: xxx
themeHeaderImage: https://xxx.png
---
```

Instead of having to write both:
```md
---
title: xxx
themeHeaderImage: https://xxx.png
eyeCatchImage: https://xxx.png
---
```

**Comment by tea3** [comment]
@xaoxuu 
I see. Actually , this plugin supports the `postImage` and `ampSettings` attributes in addition to `eyeCatchImage`. Can't be customized, but can these attributes use?
https://github.com/tea3/hexo-related-popular-posts/blob/5f782be6d13008eedd862049689df0a014dbfdb3/lib/collector.js#L50

**Comment by xaoxuu** [comment]
I submitted a pr about this, you can see if it works.

**Comment by tea3** [comment]
@xaoxuu
Thank you for suggestion. I want to merge tonight or tomorrow. Please wait for 🙏🏻

**Comment by xaoxuu** [comment]
Thank you 🤝
