### ISSUE TITLE
integrity checksum failed

### ISSUE THREAD

**Issue by atlas555** [tea3/hexo-related-popular-posts#5]
hi,thank you for excellent tool , but on mac ,this error occur,
npm ERR! code EINTEGRITY
npm ERR! sha1-Sqvzm8zti4rZLQB6BKJr5tqEd8k= integrity checksum failed when using sha1: wanted sha1-Sqvzm8zti4rZLQB6BKJr5tqEd8k= but got sha1-c+vhx0GvE4Ju9Bb0cV4uiAB7u8M=. (1436215 bytes)
what can i do?
debug log:
871 error code EINTEGRITY
872 error sha1-Sqvzm8zti4rZLQB6BKJr5tqEd8k= integrity checksum failed when using sha1: wanted sha1-Sqvzm8zti4rZLQB6BKJr5tqEd8k= but got sha1-c+vhx0GvE4Ju9Bb0cV4uiAB7u8M=. (1436215 bytes)
873 verbose exit [ 1, true ]

**Comment by tea3** [comment]
@atlas555 
Do this error occur on other plugin ? I don't know exactly , it seems to npm problem. Will you the following issue helpful ?
https://github.com/cncjs/cncjs/issues/172

**Comment by tea3** [comment]
https://github.com/npm/npm/issues/16861

**Comment by tea3** [comment]
https://github.com/nodejs/node/issues/13635
