### ISSUE TITLE
If there is no posts, the function should return empty

### ISSUE THREAD

**Issue by huyingjie** [tea3/hexo-related-popular-posts#9]
I want to hide the text "Related Posts" if no posts are returned.

When there is no posts matched, `popular_posts( {} , page )`  returns 
```
<ul class="popular-posts"><li class="popular-posts-item"><div class="popular-posts-title"><h3><a href="/untitled/" title="" rel="bookmark"></a></h3></div></li></ul>
```
It makes me impossible to write `if` statement to judge whether there exists at least related post  or not.

I think `popular_posts( {} , page )` should return empty string or any value equivalent to empty if no posts are related to the current post.

**Comment by tea3** [comment]
@huyingjie 
Actually, this plugin have a more complicated problem. Sorry , I'll fix this problem someday . Please wait until update this plugin.

This problem can be temporarily avoided with the `hexo clean` command. And if you use [cache](https://github.com/tea3/hexo-related-popular-posts/wiki/More-Settings#cache) , please delete cache file.

Also, you can judge freely in [custom html](https://github.com/tea3/hexo-related-popular-posts/wiki/More-Settings#customize-html). Please use `popular_posts_json()` tag.

**Comment by huyingjie** [comment]
@tea3 `hexo clean` does not work.

**Comment by tea3** [comment]
@huyingjie  I see . Which theme do you use ?

Also, could you avoid this issue temporarily with the [popular_posts_json()](https://github.com/tea3/hexo-related-popular-posts/wiki/More-Settings#customize-html) tag ? This tag makes me possible to judge whether there exists posts .

**Comment by huyingjie** [comment]
https://github.com/huyingjie/hexo-theme-A-RSnippet

**Comment by tea3** [comment]
@huyingjie 
Have you confirmed that the same problem will occur with [default theme](https://github.com/hexojs/hexo-theme-landscape) ?
